POST http://localhost:8080/register
Content-Type: application/json

{
  "full_name" : "test db",
  "email" : "test@gmail.com",
  "password" : "test123"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email" : "test@gmail.com",
  "password" : "test123"
}